name: ğŸš€ Build e Push Docker para AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout do cÃ³digo
        uses: actions/checkout@v3

      - name: ğŸ”§ Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ğŸ”¨ Build com Maven
        run: mvn clean package -DskipTests

      - name: ğŸ“‚ Verificar o conteÃºdo do diretÃ³rio target
        run: ls -la target/

      - name: ğŸ” Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: ğŸ” Login no AWS ECR
        id: login-ecr
        run: |
          echo "Logando no ECR..."
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: ğŸ—ï¸ Construir a Imagem Docker
        id: build-image
        run: |
          echo "Construindo a imagem Docker..."
          docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .

      - name: ğŸ·ï¸ Taggear a Imagem Docker
        id: tag-image
        run: |
          echo "Taggeando a imagem Docker..."
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      - name: ğŸš€ Enviar imagem Docker para o ECR
        id: push-image
        run: |
          echo "Enviando a imagem Docker para o ECR..."
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest